---
- hosts: all

  tasks:
    - name: Load secret variables
      ansible.builtin.include_vars: secrets.yml
      tags: [always]

    - name: Include network specific vars
      ansible.builtin.include_vars: network.yml
      tags: [always]

    - name: Install Docker prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Include main vars
      ansible.builtin.include_vars: main.yml
      tags: [always]

    - name: Include default vars
      ansible.builtin.include_vars: defaults/main.yml
      tags: [always]

    - name: Create Docker network
      docker_network:
        name: babylon-validator-net
        state: present

    - name: Include task babylon
      include_tasks: tasks/babylon.yml
      tags: babylon

    - name: Include task monitoring
      include_tasks: tasks/monitoring.yml
      tags: monitoring  

    - name: Install watchdog
      ansible.builtin.import_tasks: tasks/watchdog.yml
      tags: watchdog
