[Application Options]
; Logging level for all subsystems
LogLevel = debug

; Type of keyring to use
KeyringBackend = test

; Possible database to choose as backend
Backend = bbolt

; The name of the database
Name = default

; the listener for RPC connections, e.g., 127.0.0.1:1234
RpcListener = {{ eots_manager_name }}:12582
